<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { withBase } from 'vitepress'
import FlashTool from './FlashTool.vue'

const props = defineProps<{ locale?: string }>()

const isEn = computed(() => props.locale === 'en')

interface ManifestEntry {
  id: string
  label: string
  bin: string
}

interface Manifest {
  version: string
  date: string
  examples: ManifestEntry[]
}

const CUSTOM_ID = '__custom__'

const manifest = ref<Manifest | null>(null)
const manifestError = ref('')
const selected = ref('')

// Custom firmware state
const customBinData = ref<string | null>(null)
const customFileName = ref('')
const customFileSize = ref(0)
const isDragOver = ref(false)

const isCustom = computed(() => selected.value === CUSTOM_ID)

const selectedEntry = computed(() =>
  manifest.value?.examples.find(e => e.id === selected.value) ?? null
)

const customReady = computed(() => isCustom.value && customBinData.value !== null)

onMounted(async () => {
  try {
    const res = await fetch(withBase('/firmware/manifest.json'))
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data: Manifest = await res.json()
    manifest.value = data
    if (data.examples.length > 0) selected.value = data.examples[0].id
  } catch (e: any) {
    manifestError.value = e?.message ?? String(e)
  }
})

function readBinFile(file: File) {
  if (!file.name.endsWith('.bin')) return
  customFileName.value = file.name
  customFileSize.value = file.size
  const reader = new FileReader()
  reader.onload = e => { customBinData.value = e.target!.result as string }
  reader.readAsBinaryString(file)
}

function onFileInput(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0]
  if (file) readBinFile(file)
}

function onDrop(e: DragEvent) {
  isDragOver.value = false
  const file = e.dataTransfer?.files?.[0]
  if (file) readBinFile(file)
}

function formatSize(bytes: number) {
  return bytes >= 1024 * 1024
    ? `${(bytes / 1024 / 1024).toFixed(1)} MB`
    : `${(bytes / 1024).toFixed(0)} KB`
}
</script>

<template>
  <ClientOnly>
    <div class="flash-hub">
      <!-- Firmware not yet published -->
      <div v-if="manifestError" class="flash-hub-notice">
        <span>{{ isEn ? '⚠ Firmware not yet published.' : '⚠ 固件尚未发布。' }}</span>
        <span class="flash-hub-notice-sub">
          {{ isEn
            ? 'Binaries are generated by CI after each push to main. Check back later.'
            : '固件由 CI 在每次推送到 main 后自动构建，稍后再试。' }}
        </span>
      </div>

      <template v-else-if="manifest">
        <div class="flash-hub-meta">
          <span class="flash-hub-version">{{ manifest.version }}</span>
          <span class="flash-hub-date">{{ manifest.date.slice(0, 10) }}</span>
        </div>

        <div class="flash-hub-select-row">
          <label class="flash-hub-label" for="example-select">
            {{ isEn ? 'Select example:' : '选择示例：' }}
          </label>
          <select id="example-select" v-model="selected" class="flash-hub-select">
            <option v-for="ex in manifest.examples" :key="ex.id" :value="ex.id">
              {{ ex.label }}
            </option>
            <option disabled>──────────</option>
            <option :value="CUSTOM_ID">
              {{ isEn ? '⬆ Custom firmware…' : '⬆ 自定义固件…' }}
            </option>
          </select>
        </div>

        <!-- Custom firmware file picker -->
        <div v-if="isCustom" class="flash-hub-custom">
          <div
            class="flash-hub-dropzone"
            :class="{ 'is-over': isDragOver, 'has-file': customBinData }"
            @dragover.prevent="isDragOver = true"
            @dragleave="isDragOver = false"
            @drop.prevent="onDrop"
            @click="($refs.fileInput as HTMLInputElement).click()"
          >
            <input
              ref="fileInput"
              type="file"
              accept=".bin"
              style="display:none"
              @change="onFileInput"
            />
            <template v-if="customBinData">
              <span class="flash-hub-dropzone-icon">✓</span>
              <span class="flash-hub-dropzone-name">{{ customFileName }}</span>
              <span class="flash-hub-dropzone-size">{{ formatSize(customFileSize) }}</span>
              <span class="flash-hub-dropzone-change">{{ isEn ? 'click to change' : '点击更换' }}</span>
            </template>
            <template v-else>
              <span class="flash-hub-dropzone-icon">📂</span>
              <span>{{ isEn ? 'Drop .bin file here or click to select' : '拖拽 .bin 文件到此处，或点击选择' }}</span>
            </template>
          </div>
          <div class="flash-hub-custom-warning">
            <span class="flash-hub-warning-icon">⚠</span>
            <span>{{ isEn
              ? 'Only OSRCORE (ESP32-S3) boards are supported. The tool will abort if a different chip is detected.'
              : '仅支持 OSRCORE（ESP32-S3）开发板。连接后检测到其他芯片型号将自动中止，不会写入任何数据。' }}
            </span>
          </div>
        </div>

        <!-- Flash tool for manifest examples -->
        <FlashTool
          v-if="selectedEntry"
          :key="selected"
          :example="selected"
          :bin-url="selectedEntry.bin"
          :label="selectedEntry.label"
        />

        <!-- Flash tool for custom firmware -->
        <FlashTool
          v-else-if="customReady"
          :key="customFileName"
          :example="CUSTOM_ID"
          :bin-data="customBinData!"
          :label="customFileName"
        />
      </template>

      <!-- Loading -->
      <div v-else class="flash-hub-loading">
        <span class="flash-hub-spinner" />
        {{ isEn ? 'Loading firmware manifest…' : '加载固件清单…' }}
      </div>
    </div>
  </ClientOnly>
</template>

<style scoped>
.flash-hub { margin: 20px 0; }

.flash-hub-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
}

.flash-hub-version {
  font-family: var(--vp-font-family-mono);
  font-size: 12px;
  background: rgba(34,197,94,0.12);
  color: var(--vp-c-brand-1);
  border: 1px solid rgba(34,197,94,0.25);
  border-radius: 999px;
  padding: 2px 9px;
}

.flash-hub-date {
  font-size: 12px;
  color: var(--vp-c-text-3);
}

.flash-hub-select-row {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 16px;
}

.flash-hub-label {
  font-size: 14px;
  font-weight: 500;
  color: var(--vp-c-text-2);
  white-space: nowrap;
}

.flash-hub-select {
  flex: 1;
  max-width: 360px;
  padding: 7px 12px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  background: var(--vp-c-bg);
  color: var(--vp-c-text-1);
  font-size: 14px;
  cursor: pointer;
  outline: none;
}
.flash-hub-select:focus { border-color: var(--vp-c-brand-1); }

/* Custom firmware section */
.flash-hub-custom {
  margin-bottom: 16px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.flash-hub-dropzone {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 14px 18px;
  border: 2px dashed var(--vp-c-divider);
  border-radius: 10px;
  cursor: pointer;
  font-size: 13px;
  color: var(--vp-c-text-2);
  transition: border-color 0.15s, background 0.15s;
  user-select: none;
}
.flash-hub-dropzone:hover,
.flash-hub-dropzone.is-over {
  border-color: var(--vp-c-brand-1);
  background: rgba(34,197,94,0.04);
}
.flash-hub-dropzone.has-file {
  border-style: solid;
  border-color: rgba(34,197,94,0.4);
  background: rgba(34,197,94,0.04);
}

.flash-hub-dropzone-icon { font-size: 18px; flex-shrink: 0; }

.flash-hub-dropzone-name {
  font-family: var(--vp-font-family-mono);
  font-size: 13px;
  color: var(--vp-c-text-1);
  font-weight: 500;
}

.flash-hub-dropzone-size {
  font-size: 12px;
  color: var(--vp-c-text-3);
}

.flash-hub-dropzone-change {
  margin-left: auto;
  font-size: 11px;
  color: var(--vp-c-text-3);
}

.flash-hub-custom-warning {
  display: flex;
  align-items: flex-start;
  gap: 6px;
  padding: 8px 12px;
  border-radius: 7px;
  background: rgba(239,68,68,0.06);
  border: 1px solid rgba(239,68,68,0.2);
  font-size: 12px;
  color: var(--vp-c-text-2);
  line-height: 1.5;
}

.flash-hub-warning-icon {
  color: #ef4444;
  flex-shrink: 0;
  font-size: 13px;
}

.flash-hub-notice {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 12px 16px;
  border-radius: 8px;
  background: rgba(245,158,11,0.08);
  border: 1px solid rgba(245,158,11,0.25);
  font-size: 14px;
  color: #d97706;
}
.flash-hub-notice-sub { font-size: 12px; color: var(--vp-c-text-3); }

.flash-hub-loading {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  color: var(--vp-c-text-3);
  padding: 12px 0;
}

.flash-hub-spinner {
  width: 14px; height: 14px;
  border: 2px solid var(--vp-c-divider);
  border-top-color: var(--vp-c-brand-1);
  border-radius: 50%;
  animation: spin 0.7s linear infinite;
  flex-shrink: 0;
}
@keyframes spin { to { transform: rotate(360deg); } }
</style>
