<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useData, withBase } from 'vitepress'
import FlashTool from './FlashTool.vue'

const props = defineProps<{ locale?: string }>()

const isEn = computed(() => props.locale === 'en')

interface ManifestEntry {
  id: string
  label: string
  bin: string
}

interface Manifest {
  version: string
  date: string
  examples: ManifestEntry[]
}

const manifest = ref<Manifest | null>(null)
const manifestError = ref('')
const selected = ref('')

const selectedEntry = computed(() =>
  manifest.value?.examples.find(e => e.id === selected.value) ?? null
)

onMounted(async () => {
  try {
    const res = await fetch(withBase('/firmware/manifest.json'))
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data: Manifest = await res.json()
    manifest.value = data
    if (data.examples.length > 0) selected.value = data.examples[0].id
  } catch (e: any) {
    manifestError.value = e?.message ?? String(e)
  }
})
</script>

<template>
  <ClientOnly>
    <div class="flash-hub">
      <!-- Firmware not yet published -->
      <div v-if="manifestError" class="flash-hub-notice">
        <span>{{ isEn ? '⚠ Firmware not yet published.' : '⚠ 固件尚未发布。' }}</span>
        <span class="flash-hub-notice-sub">
          {{ isEn
            ? 'Binaries are generated by CI after each push to main. Check back later.'
            : '固件由 CI 在每次推送到 main 后自动构建，稍后再试。' }}
        </span>
      </div>

      <template v-else-if="manifest">
        <div class="flash-hub-meta">
          <span class="flash-hub-version">{{ manifest.version }}</span>
          <span class="flash-hub-date">{{ manifest.date.slice(0, 10) }}</span>
        </div>

        <div class="flash-hub-select-row">
          <label class="flash-hub-label" for="example-select">
            {{ isEn ? 'Select example:' : '选择示例：' }}
          </label>
          <select id="example-select" v-model="selected" class="flash-hub-select">
            <option v-for="ex in manifest.examples" :key="ex.id" :value="ex.id">
              {{ ex.label }}
            </option>
          </select>
        </div>

        <FlashTool
          v-if="selectedEntry"
          :key="selected"
          :example="selected"
          :bin-url="selectedEntry.bin"
          :label="selectedEntry.label"
        />
      </template>

      <!-- Loading -->
      <div v-else class="flash-hub-loading">
        <span class="flash-hub-spinner" />
        {{ isEn ? 'Loading firmware manifest…' : '加载固件清单…' }}
      </div>
    </div>
  </ClientOnly>
</template>

<style scoped>
.flash-hub { margin: 20px 0; }

.flash-hub-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
}

.flash-hub-version {
  font-family: var(--vp-font-family-mono);
  font-size: 12px;
  background: rgba(34,197,94,0.12);
  color: var(--vp-c-brand-1);
  border: 1px solid rgba(34,197,94,0.25);
  border-radius: 999px;
  padding: 2px 9px;
}

.flash-hub-date {
  font-size: 12px;
  color: var(--vp-c-text-3);
}

.flash-hub-select-row {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 16px;
}

.flash-hub-label {
  font-size: 14px;
  font-weight: 500;
  color: var(--vp-c-text-2);
  white-space: nowrap;
}

.flash-hub-select {
  flex: 1;
  max-width: 360px;
  padding: 7px 12px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  background: var(--vp-c-bg);
  color: var(--vp-c-text-1);
  font-size: 14px;
  cursor: pointer;
  outline: none;
}
.flash-hub-select:focus { border-color: var(--vp-c-brand-1); }

.flash-hub-notice {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 12px 16px;
  border-radius: 8px;
  background: rgba(245,158,11,0.08);
  border: 1px solid rgba(245,158,11,0.25);
  font-size: 14px;
  color: #d97706;
}
.flash-hub-notice-sub { font-size: 12px; color: var(--vp-c-text-3); }

.flash-hub-loading {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  color: var(--vp-c-text-3);
  padding: 12px 0;
}

.flash-hub-spinner {
  width: 14px; height: 14px;
  border: 2px solid var(--vp-c-divider);
  border-top-color: var(--vp-c-brand-1);
  border-radius: 50%;
  animation: spin 0.7s linear infinite;
  flex-shrink: 0;
}
@keyframes spin { to { transform: rotate(360deg); } }
</style>
